log:
  # "debug" "info" "warn" "error"
  level: "warn"
  file: "./mosdns.log"
api:
  http: 0.0.0.0:9091
include: ["./dns.yaml"]
plugins:
  - tag: hosts
    type: hosts
    args:
      entries:
        - "mbp.mylocal.com 192.168.31.5"
  - tag: lazy_cache
    type: cache
    args:
      size: 4096
      lazy_cache_ttl: 86400
      dump_file: "./cache.dump"
      dump_interval: 600

  - tag: accept_resp
    type: sequence
    args:
      - matches: "!has_resp"
        exec: return
      - exec: ttl 1800
      - exec: accept

  - tag: handle_hosts
    type: sequence
    args:
      - exec: "$hosts"
      - matches: "!has_resp"
        exec: return
      - exec: "query_summary from hosts"
      - exec: jump accept_resp

  - tag: handle_cache
    type: sequence
    args:
      - exec: "$lazy_cache"
      - matches: "!has_resp"
        exec: return
      - exec: "query_summary from cache"
      - exec: jump accept_resp

  - tag: handle_qtype65
    type: sequence
    args:
      - matches: "!qtype 65"
        exec: return
      - exec: "query_summary handle qtype65"
      - exec: reject 3

  - tag: handle_ptr
    type: sequence
    args:
      - matches: "!qtype 12"
        exec: return
      - exec: "query_summary handle ptr"
      - exec: $forward_dnsmasq
      - exec: accept

  - tag: handle_lan
    type: sequence
    args:
      - matches: "!qname domain:lan"
        exec: return
      - exec: "query_summary handle lan"
      - exec: $forward_dnsmasq
      - exec: accept

  - tag: pre_seq
    type: sequence
    args:
      - exec: jump handle_hosts
      - exec: jump handle_qtype65
      - exec: jump handle_lan
      - exec: jump handle_ptr

  - tag: local_seq
    type: sequence
    args:
      - exec: "query_summary local dns"
      - exec: "$forward_local"
      - exec: jump accept_resp

  - tag: main_sequence
    type: sequence
    args:
      - exec: jump pre_seq
      - exec: jump handle_cache
      - exec: prefer_ipv4
      - exec: jump local_seq
      - exec: "query_summary has no resp"
  - tag: udp_server
    type: udp_server
    args:
      entry: main_sequence
      listen: ":53"
  - tag: tcp_server
    type: tcp_server
    args:
      entry: main_sequence
      listen: ":5335"
